apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "locust.master" . }}
  labels:
    app: {{ template "locust.fullname" . }}
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    component: master
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: {{ default 1 .Values.master.maxSurge }}
      maxUnavailable: {{ default 1 .Values.master.maxUnavailable }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/worker-cm.yaml") . | sha256sum }}
      labels:
        release: {{ .Release.Name | quote }}
        app: {{ template "locust.fullname" . }}
        component: "master"
    spec:
    {{- if .Values.image.pullSecrets }}
      imagePullSecrets:
{{ toYaml .Values.image.pullSecrets | indent 8 }}
    {{- end }}
      containers:
      - name: locust
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        args: ["-f", "/tasks/{{ .Values.locustFile.filename }}", "--host", "{{ .Values.targetHost }}", "--master"]
        resources:
{{ toYaml .Values.worker.resources | indent 10 }}
        ports:
        - containerPort: {{ .Values.service.internalPort }}
          name: loc-master-web
          protocol: TCP
        - containerPort: 5557
          name: loc-master-p1
          protocol: TCP
        - containerPort: 5558
          name: loc-master-p2
          protocol: TCP
        volumeMounts:
          - name: locustfile
            mountPath: /tasks/
        livenessProbe:
          periodSeconds: 10
          httpGet:
            path: /
            port: {{ .Values.service.internalPort }}
        readinessProbe:
          periodSeconds: 10
          httpGet:
            path: /
            port: {{ .Values.service.internalPort }}
      volumes:
      - name: locustfile
        configMap:
          name: {{ template "locust.worker-configmap" . }}
      restartPolicy: Always
